### ISSUE TITLE
Estimate risk analysis

### ISSUE THREAD

**Issue by AliaMostafa** [AliaMostafa/Pharmacy-Software-System#33]

**Comment by AliaMostafa** [comment]
- Estimate possible risks
- Analyze risks root problems
- Identify risk size
- Suggest potential risk reduction solutions

**Comment by ziad-ahmed-2004** [comment]
risk analysis is Done

**Comment by ziad-ahmed-2004** [comment]
[Risk Identification.docx](https://github.com/user-attachments/files/18217004/Risk.Identification.docx)
